services:
  - type: web
    name: chinese-poker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AI_PROGRESS_TOKEN
        sync: false
      - key: PORT
        value: 10000
